#!/bin/bash

#Tao 5 File Tu User2_1.txt Den User2_5.txt
For i in {1..5}
Do 
	Touch user2_$i.txt
#Them Noi Dung User2 Init Vao Cac File Co N le
If [ $((i % 2)) -ne 0]; then
Echo "User 2 init" > user_$i.txt
Fi
Done
